import {
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'
import { ADMIN, USER } from 'constants/roles.constant'
const navigationConfig = [
    {
        key: 'Dashboard',
        path: '/Dashboard',
        title: 'Home',
        translateKey: 'nav.Dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
    {
        key: 'Admin',
        path: '',
        title: 'Admin',
        translateKey: 'Admin',
        icon: 'groupSingleMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'UserManagement',
                path: '',
                icon: 'FcConferenceCall',
                title: 'User Management',
                translateKey: 'UserManagement',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'employeemaster',
                        path: '/employee',
                        title: 'Employee Master',
                        translateKey: 'employeemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'ChannelSettings',
                path: '',
                title: 'Channel Settings',
                icon: 'FcSettings',
                translateKey: 'nav.ChannelSettings',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'channelmaster',
                        path: '/channel',
                        title: 'Channel Master',
                        translateKey: 'nav.channelmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'entitymaster',
                        path: '/entity',
                        title: 'Entity Master',
                        translateKey: 'nav.entitymaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'locationmaster',
                        path: '/location',
                        title: 'Location Master',
                        translateKey: 'nav.locationmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'CommonManagement',
                path: '',
                icon: 'FcCollaboration',
                title: 'Common Master',
                translateKey: 'nav.CommonManagement',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'currencymaster',
                        path: '/currency',
                        title: 'Currency Master',
                        translateKey: 'nav.currencymaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'designationMaster',
                        path: '/designation',
                        title: 'Designation Master',
                        translateKey: 'nav.designationMaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'departmentmaster',
                        path: '/department',
                        title: 'Department Master',
                        translateKey: 'nav.departmentmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'languagemaster',
                        path: '/language',
                        title: 'Language Master',
                        translateKey: 'nav.languagemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'placemaster.item2',
                        path: '/placemaster',
                        title: 'Place Master',
                        translateKey: 'nav.placemaster.item2',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'timezonemaster',
                        path: '/timezone',
                        title: 'TimeZone Master',
                        translateKey: 'nav.timezonemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'regionmaster',
                        path: '/region',
                        title: 'Region Master',
                        translateKey: 'nav.regionmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'statemaster',
                        path: '/statemaster',
                        title: 'State Master',
                        translateKey: 'nav.statemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'zonemaster',
                        path: '/zone',
                        title: 'Zone Master',
                        translateKey: 'nav.zonemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'SystemSettings',
                path: '',
                icon: 'FcSettings',
                title: 'System Settings',
                translateKey: 'nav.SystemSettings',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'formmaster',
                        path: '/form',
                        title: 'Form Master',
                        translateKey: 'nav.formmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'modulemaster',
                        path: '/module',
                        title: 'Module Master',
                        translateKey: 'nav.modulemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'submodulemaster',
                        path: '/submodule',
                        title: 'SubModule Master',
                        translateKey: 'nav.submodulemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
    {
        key: 'Programming',
        path: '/Programming',
        title: 'Programming',
        translateKey: 'nav.Programming',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'suppliermastertable',
                path: '',
                icon: 'FcPlanner',
                title: 'Content Management',
                translateKey: 'nav.suppliermastertable',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'viewmaster',
                        path: '/viewmaster',
                        title: 'Audience View Master',
                        translateKey: 'nav.viewmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'aspectratiomaster',
                        path: '/aspectratiomaster',
                        title: 'AspectRatio Master',
                        translateKey: 'nav.aspectratiomaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'awardmaster',
                        path: '/awardmaster',
                        title: 'Award Master..',
                        translateKey: 'nav.awardmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'contenttypemaster',
                        path: '/contenttypemaster',
                        title: 'Content Type  Master',
                        translateKey: 'nav.contenttypemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'contentsegmaster',
                        path: '/contentsegmaster',
                        title: 'Content Segment Master',
                        translateKey: 'nav.contentsegmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'contentmaster',
                        path: '/contentmaster',
                        title: 'Content Master',
                        translateKey: 'nav.contentmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'commercialtypemaster',
                        path: '/commercialtypemaster',
                        title: 'CommercialType Master',
                        translateKey: 'nav.commercialtypemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'Censorshipmaster',
                        path: '/Censorshipmaster',
                        title: 'Censorship Master',
                        translateKey: 'nav.Censorshipmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'fillertypemaster',
                        path: '/fillertypemaster',
                        title: 'FillerType Master',
                        translateKey: 'nav.fillertypemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'genremaster',
                        path: '/genremaster',
                        title: 'Genre Master',
                        translateKey: 'nav.genremaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'fpcorgrep',
                        path: '/fpcorgrep',
                        title: 'OriginalRepeat Master..',
                        translateKey: 'nav.fpcorgrep',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'starcasttype',
                        path: '/starcasttype',
                        title: 'StarCastType Master',
                        translateKey: 'nav.starcasttype',
                        icon: 'singleMenu',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'starcastmaster',
                        path: '/starcastmaster',
                        title: 'Starcast Master',
                        translateKey: 'nav.starcastmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'SubGenreMaster',
                        path: '/SubGenreMaster',
                        title: 'SubGenre Master',
                        translateKey: 'nav.SubGenreMaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'Telecastmaster',
                        path: '/Telecastmaster',
                        title: 'Telecast Master',
                        translateKey: 'nav.Telecastmaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'promotypemaster',
                        path: '/promotypemaster',
                        title: 'PromoType Master',
                        translateKey: 'nav.promotypemaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'patterMaster',
                        path: '/patterMaster',
                        title: 'Patter Master',
                        translateKey: 'nav.patterMaster',
                        icon: 'FcFilingCabinet',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]

export default navigationConfig
