import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'

const navigationConfig = [
    {
        key: 'Dashboard',
        path: '/Dashboard',
        title: 'Home',
        translateKey: 'nav.Dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'Admin',
        path: '',
        title: 'Admin',
        translateKey: 'nav.Admin.Admin',
        icon: 'groupSingleMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'employeemaster',
                path: '/employee',
                title: 'Employee Master',
                translateKey: 'nav.employeemaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'entitymaster',
                path: '/entity',
                title: 'Entity Master',
                translateKey: 'nav.entitymaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'locationmaster',
                path: '/location',
                title: 'Location Master',
                translateKey: 'nav.locationmaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'departmentmaster',
                path: '/department',
                title: 'Department Master',
                translateKey: 'nav.departmentmaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'zonemaster',
                path: '/zone',
                title: 'Zone Master',
                translateKey: 'nav.zonemaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'timezonemaster',
                path: '/timezone',
                title: 'TimeZone Master',
                translateKey: 'nav.timezonemaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },

            {
                key: 'regionmaster',
                path: '/region',
                title: 'Region Master',
                translateKey: 'nav.regionmaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'formmaster',
                path: '/form',
                title: 'Form Master',
                translateKey: 'nav.formmaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'channelmaster',
                path: '/channel',
                title: 'Channel Master',
                translateKey: 'nav.channelmaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'languagemaster',
                path: '/language',
                title: 'Language Master',
                translateKey: 'nav.languagemaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'modulemaster',
                path: '/module',
                title: 'Module Master',
                translateKey: 'nav.modulemaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'submodulemaster',
                path: '/submodule',
                title: 'SubModule Master',
                translateKey: 'nav.submodulemaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'currencymaster',
                path: '/currency',
                title: 'Currency Master',
                translateKey: 'nav.currencymaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'designationMaster',
                path: '/designation',
                title: 'Designation Master',
                translateKey: 'nav.designationMaster',
                icon: 'HiAcademicCap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'placemaster.item2',
                path: '/placemaster',
                title: 'Place Master',
                translateKey: 'nav.placemaster.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'Programming',
        path: '/Programming',
        title: 'Content',
        translateKey: 'nav.Programming',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'suppliermastertable.item2',
                path: '/suppliermastertable',
                title: 'Supplier Master',
                translateKey: 'nav.suppliermastertable.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'starcasttype.item2',
                path: '/starcasttype',
                title: 'StarCastType Master',
                translateKey: 'nav.starcasttype.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'starcastmaster.item2',
                path: '/starcastmaster',
                title: 'Starcast Master',
                translateKey: 'nav.starcastmaster.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'genremaster.item2',
                path: '/genremaster',
                title: 'Genre Master',
                translateKey: 'nav.genremaster.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'SubGenreMaster.item2',
                path: '/SubGenreMaster',
                title: 'SubGenre Master',
                translateKey: 'nav.SubGenreMaster.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'contenttypemaster.item2',
                path: '/contenttypemaster',
                title: 'Content Type  Master',
                translateKey: 'nav.contenttypemaster.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'viewmaster.item2',
                path: '/viewmaster',
                title: 'View Master',
                translateKey: 'nav.viewmaster.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'Censorshipmaster.item2',
                path: '/Censorshipmaster',
                title: 'Censorship Master',
                translateKey: 'nav.Censorshipmaster.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'Telecastmaster.item2',
                path: '/Telecastmaster',
                title: 'Telecast Master',
                translateKey: 'nav.Telecastmaster.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    /** Example purpose only, please remove */
    // {
    //     key: 'singleMenuItem',
    //     path: '/single-menu-view',
    //     title: 'Single menu item',
    //     translateKey: 'nav.singleMenuItem',
    //     icon: 'singleMenu',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'collapseMenu',
    //     path: '',
    //     title: 'Collapse Menu',
    //     translateKey: 'nav.collapseMenu.collapseMenu',
    //     icon: 'collapseMenu',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'collapseMenu.item1',
    //             path: '/collapse-menu-item-view-1',
    //             title: 'Collapse menu item 1',
    //             translateKey: 'nav.collapseMenu.item1',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'collapseMenu',
    //             path: '/collapse-menu-item-view-2',
    //             title: 'Collapse menu item 2',
    //             translateKey: 'nav.collapseMenu',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    // {
    //     key: 'groupMenu',
    //     path: '',
    //     title: 'Group Menu',
    //     translateKey: 'nav.groupMenu.groupMenu',
    //     icon: '',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'Group single menu item',
    //             translateKey: 'nav.groupMenu.single',
    //             icon: 'groupSingleMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'groupMenu.collapse',
    //             path: '',
    //             title: 'Group collapse menu',
    //             translateKey: 'nav.groupMenu.collapse.collapse',
    //             icon: 'groupCollapseMenu',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [],
    //             subMenu: [
    //                 {
    //                     key: 'groupMenu.collapse.item1',
    //                     path: '/group-collapse-menu-item-view-1',
    //                     title: 'Menu item 1',
    //                     translateKey: 'nav.groupMenu.collapse.item1',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'groupMenu.collapse.item2',
    //                     path: '/group-collapse-menu-item-view-2',
    //                     title: 'Menu item 2',
    //                     translateKey: 'nav.groupMenu.collapse.item2',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
]

export default navigationConfig
