const channel = [
    {
        asterisk: true,
        lable: 'Channel Name',
        placeholder: 'Channel Name',
        name: 'ChannelName',
        type: 'text',
        width: '50%',
    },
    {
        asterisk: true,
        lable: 'ShortName',
        placeholder: 'ShortName',
        name: 'ShortName',
        type: 'text',
        width: '50%',
    },
    {
        asterisk: true,
        lable: 'Channel Genre',
        placeholder: 'Channel Genre',
        name: 'ChannelGenre',
        type: 'text',
        width: '50%',
    },
    {
        asterisk: true,
        lable: ' Channel Content Type',
        placeholder: 'Channel Content Type',
        name: 'ChannelContentType',
        type: 'text',
        width: '50%',
    },
    {
        asterisk: true,
        lable: 'SAC Code',
        placeholder: 'SAC Code',
        name: 'SACCode',
        type: 'text',
        width: '50%',
    },
    {
        asterisk: true,
        lable: 'GSTN Number',
        placeholder: 'GSTN Number',
        name: 'GSTN_id',
        type: 'text',
        width: '50%',
    },
    // {
    //     cats: 'text',
    //     asterisk: true,
    //     lable: 'Address',
    //     placeholder: 'Corp Address',
    //     name: 'CorpAddress',
    //     type: 'text',
    //     width: '50%',
    // },
    // {
    //     cats: 'text',
    //     asterisk: true,
    //     lable: 'Contact Person',
    //     placeholder: 'Contact Person',
    //     name: 'ContactPerson',
    //     type: 'text',
    //     width: '50%',
    // },
]
export default channel
