const enity = [
    {
        category: 'text',
        asterisk: true,
        lable: 'Name',
        placeholder: 'Entity Name',
        name: 'entityname',
        type: 'text',
        width: '50%',
        max: 100,
    },
    {
        category: 'number',
        asterisk: true,
        lable: 'Contact',
        placeholder: 'Contact',
        name: 'Contact',
        type: 'number',
        width: '50%',
    },
    {
        category: 'text',
        asterisk: true,
        lable: 'Parmanet Address',
        placeholder: 'Parmanet Address',
        name: 'PermAddress',
        type: 'text',
        width: '100%',
    },
    {
        category: 'text',
        asterisk: true,
        lable: 'Corporate Address',
        placeholder: 'Corporate Address',
        name: 'CorpAddress',
        type: 'text',
        width: '100%',
    },
    {
        category: 'text',
        asterisk: true,
        lable: 'Contact Person',
        placeholder: 'Contact Person',
        name: 'ContactPerson',
        type: 'text',
        width: '50%',
    },
    {
        category: 'text',
        asterisk: true,
        lable: 'PAN NO',
        placeholder: 'PAN NO',
        name: 'PANNO',
        type: 'text',
        width: '50%',
    },
    {
        category: 'text',
        asterisk: true,
        lable: 'CIN Number',
        placeholder: 'CIN Number',
        name: 'CINNumber',
        type: 'text',
        width: '50%',
    },
    {
        category: 'Status',
        asterisk: true,
        lable: 'Status',
        name: 'IsActive',
        width: '50%',
    },
]
export default enity
